description = "Executes the BMad Task: Analyze Story Structure"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/analyze-story-structure.md}
"""