description = "Executes the BMad Task: Assemble Kdp Package"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/assemble-kdp-package.md}
"""