description = "Executes the BMad Task: Character Depth Pass"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/character-depth-pass.md}
"""