description = "Executes the BMad Task: Game Design Brainstorming"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-godot-game-dev/tasks/game-design-brainstorming.md}
"""