description = "Executes the BMad Task: Generate Cover Brief"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/generate-cover-brief.md}
"""