description = "Executes the BMad Task: Generate Scene List"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/generate-scene-list.md}
"""