description = "Executes the BMad Task: Generate Cover Prompts"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/generate-cover-prompts.md}
"""