description = "Executes the BMad Task: Incorporate Feedback"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-creative-writing/tasks/incorporate-feedback.md}
"""