description = "Executes the BMad Task: Review Infrastructure"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-infrastructure-devops/tasks/review-infrastructure.md}
"""