description = "Executes the BMad Task: Validate Infrastructure"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-infrastructure-devops/tasks/validate-infrastructure.md}
"""