description = "Executes the BMad Task: Validate Game Story"
prompt = """
CRITICAL: You are to execute the BMad Task defined below.

@{expansion-packs/bmad-godot-game-dev/tasks/validate-game-story.md}
"""